/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author Michelle
 */
public class Interfaz1 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        initComponents();

        //Esta linea de codigo sirve para que nuestra interfaz aparezca centrada
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seleccionar_archivo = new javax.swing.JButton();
        categoria = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JLabel();
        btn_subir = new javax.swing.JButton();
        archivo1 = new javax.swing.JButton();
        archivo10 = new javax.swing.JButton();
        archivo11 = new javax.swing.JButton();
        archivo12 = new javax.swing.JButton();
        archivo13 = new javax.swing.JButton();
        archivo14 = new javax.swing.JButton();
        archivo15 = new javax.swing.JButton();
        archivo16 = new javax.swing.JButton();
        archivo17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        btn_descargar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 147, 200));

        seleccionar_archivo.setBackground(new java.awt.Color(255, 204, 255));
        seleccionar_archivo.setText("Seleccionar Archivo");
        seleccionar_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionar_archivoActionPerformed(evt);
            }
        });

        categoria.setBackground(new java.awt.Color(255, 204, 204));
        categoria.setEditable(true);
        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorias", "Progrmacion", "BD", "Investigacion de Operaciones" }));

        titulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Adminstrador de Archivos");

        btn_subir.setText("Subir Archivo");
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });

        archivo1.setBackground(new java.awt.Color(204, 204, 255));
        archivo1.setText("Archivo1");

        archivo10.setBackground(new java.awt.Color(204, 255, 204));
        archivo10.setText("Archivo1");
        archivo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo10ActionPerformed(evt);
            }
        });

        archivo11.setBackground(new java.awt.Color(255, 204, 255));
        archivo11.setText("Archivo1");
        archivo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo11ActionPerformed(evt);
            }
        });

        archivo12.setBackground(new java.awt.Color(204, 204, 255));
        archivo12.setText("Archivo1");
        archivo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo12ActionPerformed(evt);
            }
        });

        archivo13.setBackground(new java.awt.Color(204, 255, 204));
        archivo13.setText("Archivo1");
        archivo13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo13ActionPerformed(evt);
            }
        });

        archivo14.setBackground(new java.awt.Color(255, 204, 255));
        archivo14.setText("Archivo1");
        archivo14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo14ActionPerformed(evt);
            }
        });

        archivo15.setBackground(new java.awt.Color(204, 204, 255));
        archivo15.setText("Archivo1");
        archivo15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo15ActionPerformed(evt);
            }
        });

        archivo16.setBackground(new java.awt.Color(204, 255, 204));
        archivo16.setText("Archivo1");
        archivo16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo16ActionPerformed(evt);
            }
        });

        archivo17.setBackground(new java.awt.Color(255, 204, 255));
        archivo17.setText("Archivo1");
        archivo17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo17ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Archivos");

        btn_borrar.setBackground(new java.awt.Color(102, 102, 255));
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setText("Borrar");

        btn_descargar.setBackground(new java.awt.Color(255, 204, 102));
        btn_descargar.setForeground(new java.awt.Color(255, 255, 255));
        btn_descargar.setText("Descargar");

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("X");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_salir)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(seleccionar_archivo)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(archivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(archivo12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(archivo15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(archivo17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btn_borrar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_descargar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_subir)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionar_archivo))
                .addGap(26, 26, 26)
                .addComponent(btn_subir)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archivo12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archivo15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_borrar)
                    .addComponent(btn_descargar))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Al precionar el boton salir se cierra el programa
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void archivo17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo17ActionPerformed

    private void archivo16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo16ActionPerformed

    private void archivo15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo15ActionPerformed

    private void archivo14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo14ActionPerformed

    private void archivo13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo13ActionPerformed

    private void archivo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo12ActionPerformed

    private void archivo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo11ActionPerformed

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_subirActionPerformed

    private void seleccionar_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionar_archivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionar_archivoActionPerformed

    private void archivo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archivo1;
    private javax.swing.JButton archivo10;
    private javax.swing.JButton archivo11;
    private javax.swing.JButton archivo12;
    private javax.swing.JButton archivo13;
    private javax.swing.JButton archivo14;
    private javax.swing.JButton archivo15;
    private javax.swing.JButton archivo16;
    private javax.swing.JButton archivo17;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_descargar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_subir;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton seleccionar_archivo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
